apiVersion: v1
kind: Namespace
metadata:
  name: ashokit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deploy-manager
  namespace: ashokit
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch","create","update","patch"]
- apiGroups: ["apps"]
  resources: ["deployments/status"]
  verbs: ["get","update","patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch","create","update","patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-manager-binding
  namespace: ashokit
subjects:
- kind: ServiceAccount
  name: jenkins-ci-sa
  namespace: jenkins-ci
roleRef:
  kind: Role
  name: jenkins-deploy-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: ashokit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: goudareddy26/ashokit:v2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: ashokit
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
