apiVersion: v1
kind: Namespace
metadata:
  name: ashokit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: ashokit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: goudareddy26/ashokit:v2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: ashokit
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
