apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: otel
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: query
      port: 16686
      targetPort: 16686
      nodePort: 31686
    - name: collector
      port: 14250
      targetPort: 14250
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.49
          ports:
            - containerPort: 16686  # UI
            - containerPort: 14250  # OTLP gRPC collector
